version: '3.8'
services:
  backend:
    build: .
    container_name: Techblog-Production
    # depends_on:
    #   - database
    ports:
      - '2000:2000'
    networks:
      - my-shared-network
    environment:
      - SECRET_KEY=${SECRET_KEY} # Example of passing environment variables
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  # database:
  #   image: mysql:latest
  #   container_name: TechBlog-Database-Test
  #   ports:
  #     - '2001:3306'
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}

networks:
  my-shared-network:
    external: true